// ==============================================
// TOOL MARK
// Each tool's favicon, inline, at whatever size the
// caller asks for.
//
// Inline SVG rather than <img src="https://…/favicon.svg">
// on purpose. A remote icon is a cross-origin request
// per row for a 16px glyph, it fails offline and on a
// preview deploy, and the unreleased tools have no
// domain to load one from. These are a handful of
// shapes; shipping them as markup costs less than the
// requests would.
//
// Every mark shares the plate: a #131210 rounded
// square with the same rx and the same 6px inset, so
// the family reads as a set and only the figure
// inside changes.
//
// SHARED FILE. Authored in ramps-studio, copied
// outward. Don't edit it downstream.
// ==============================================
import { cn } from "../utils"

const INK = "#131210"

/**
 * Figures, in the 32-unit viewBox the plate defines.
 *
 * A tool with no mark yet renders the bare plate rather than a placeholder
 * glyph — an invented symbol for an unbuilt tool is a promise about what it
 * will be, and these are quiet enough to read as "not yet".
 */
const FIGURES: Record<string, React.ReactNode> = {
  ramps: (
    <>
      <rect x="6" y="6" width="20" height="4" rx="1.2" fill="#c5d9ff" />
      <rect x="6" y="11" width="20" height="4" rx="1.2" fill="#8db0ff" />
      <rect x="6" y="16" width="20" height="4" rx="1.2" fill="#3d7dff" />
      <rect x="6" y="21" width="20" height="4" rx="1.2" fill="#2452b0" />
    </>
  ),
  // Five bars at irregular heights. Same shape as beeps.studio/favicon.svg,
  // generated by that repo's scripts/build-icons.py — change one, change both.
  //
  // It was a decaying oscillation drawn as one continuous stroke, which read
  // as a near-twin of the motion curve below: same colour, same weight, same
  // kind of drawing. Bars are a different object at a glance, and they rhyme
  // with Ramps' four horizontal bars turned a quarter turn.
  //
  // The heights are deliberately IRREGULAR — a smooth fall reads as a level
  // meter, and real audio is not monotonic.
  sound: (
    <>
      <rect x="6.00" y="11.50" width="2.8" height="9" rx="1.1" fill="#8db0ff" />
      <rect x="10.30" y="6.00" width="2.8" height="20" rx="1.1" fill="#8db0ff" />
      <rect x="14.60" y="10.00" width="2.8" height="12" rx="1.1" fill="#8db0ff" />
      <rect x="18.90" y="7.50" width="2.8" height="17" rx="1.1" fill="#8db0ff" />
      <rect x="23.20" y="12.50" width="2.8" height="7" rx="1.1" fill="#8db0ff" />
    </>
  ),
  // A coil spring, drawn literally. Same point lists as
  // springs.studio/favicon.svg — change one, change both.
  //
  // Earlier versions drew the spring's step response as two parallel strokes,
  // to give it Ramps' kind of mass. That does not work at this size: two
  // strokes stay parallel at a gap d only where the curve's radius of curvature
  // exceeds d, and a spring that rings has a radius near 0.6 units at its
  // overshoot peak against a ~2.3-unit gap, so the inner stroke folds through
  // itself. Translating down instead merges them on the steep rise; slope-
  // scaling the offset staggers them apart; capping at the local radius kinks.
  // A coil is ONE stroke, so there is no offset to fold — and it is more
  // literal. Ramps is horizontal bars, Beeps vertical bars, Springs a coil.
  //
  // An obliquely-viewed helix: x = P*t + A*sin(t), y = B*cos(t), depth = sin(t)
  // with P 0.55, A 1.6, B 3.2 over 3 turns at 40 degrees. The stroke is split on
  // the sign of that depth — BACK halves in #2452b0 first, FRONT halves over
  // them in #8db0ff — so the loops pass behind one another rather than reading
  // as a flat scribble.
  motion: (
    <>
      <polyline
        points="15.97,7.64 15.81,7.56 15.57,7.52 15.29,7.55 14.98,7.64 14.63,7.80 14.26,8.03 13.87,8.32 13.48,8.67 13.08,9.07 12.69,9.53 12.31,10.03 11.95,10.57 11.62,11.13 11.32,11.72 11.07,12.32 10.86,12.93 10.70,13.54 10.59,14.13 10.54,14.71 10.56,15.25 10.63,15.77 10.76,16.24 10.95,16.66 11.20,17.03 11.51,17.34 11.56,17.38"
        fill="none"
        stroke="#2452b0"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="20.23,11.21 20.07,11.13 19.83,11.09 19.55,11.12 19.24,11.21 18.89,11.37 18.52,11.60 18.13,11.89 17.73,12.24 17.34,12.65 16.94,13.10 16.57,13.60 16.21,14.14 15.88,14.70 15.58,15.29 15.33,15.90 15.12,16.50 14.96,17.11 14.85,17.70 14.80,18.28 14.81,18.83 14.88,19.34 15.02,19.81 15.21,20.23 15.46,20.60 15.77,20.91 15.82,20.95"
        fill="none"
        stroke="#2452b0"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="24.48,14.79 24.32,14.70 24.09,14.66 23.81,14.69 23.49,14.79 23.15,14.95 22.78,15.17 22.39,15.46 21.99,15.81 21.59,16.22 21.20,16.67 20.82,17.17 20.47,17.71 20.14,18.28 19.84,18.87 19.58,19.47 19.37,20.08 19.21,20.68 19.11,21.28 19.06,21.85 19.07,22.40 19.14,22.91 19.27,23.38 19.47,23.80 19.72,24.17 20.02,24.48"
        fill="none"
        stroke="#2452b0"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="7.31,13.81 7.61,14.01 8.01,14.19 8.46,14.31 8.95,14.36 9.47,14.34 10.01,14.26 10.56,14.11 11.13,13.90 11.70,13.64 12.26,13.33 12.81,12.97 13.34,12.58 13.84,12.15 14.31,11.71 14.73,11.25 15.11,10.78 15.44,10.32 15.72,9.87 15.94,9.44 16.10,9.03 16.20,8.66 16.23,8.34 16.21,8.06 16.13,7.83 16.00,7.66 15.97,7.64"
        fill="none"
        stroke="#8db0ff"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="11.56,17.38 11.87,17.58 12.27,17.77 12.72,17.88 13.21,17.93 13.72,17.91 14.27,17.83 14.82,17.68 15.39,17.47 15.96,17.21 16.52,16.90 17.07,16.54 17.60,16.15 18.10,15.73 18.56,15.28 18.99,14.82 19.37,14.35 19.70,13.89 19.98,13.44 20.20,13.01 20.35,12.60 20.45,12.24 20.49,11.91 20.47,11.63 20.39,11.40 20.25,11.24 20.23,11.21"
        fill="none"
        stroke="#8db0ff"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="15.82,20.95 16.12,21.16 16.53,21.34 16.98,21.45 17.47,21.50 17.98,21.48 18.52,21.40 19.08,21.25 19.65,21.05 20.22,20.78 20.78,20.47 21.33,20.12 21.86,19.72 22.36,19.30 22.82,18.85 23.25,18.39 23.63,17.93 23.96,17.46 24.23,17.01 24.45,16.58 24.61,16.18 24.71,15.81 24.75,15.48 24.73,15.20 24.65,14.98 24.51,14.81 24.48,14.79"
        fill="none"
        stroke="#8db0ff"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </>
  ),
}

export default function ToolMark({
  id,
  size = 16,
  className,
}: {
  /** Tool id from the manifest. An unknown id renders the bare plate. */
  id: string
  size?: number
  className?: string
}) {
  return (
    <svg
      viewBox="0 0 32 32"
      width={size}
      height={size}
      aria-hidden="true"
      focusable="false"
      className={cn("shrink-0", className)}
    >
      <rect width="32" height="32" rx="7" fill={INK} />
      {FIGURES[id] ?? null}
    </svg>
  )
}
