// ==============================================
// TOOL MARK
// Each tool's favicon, inline, at whatever size the
// caller asks for.
//
// Inline SVG rather than <img src="https://…/favicon.svg">
// on purpose. A remote icon is a cross-origin request
// per row for a 16px glyph, it fails offline and on a
// preview deploy, and the unreleased tools have no
// domain to load one from. These are a handful of
// shapes; shipping them as markup costs less than the
// requests would.
//
// Every mark shares the plate: a #131210 rounded
// square with the same rx and the same 6px inset, so
// the family reads as a set and only the figure
// inside changes.
//
// SHARED FILE. Authored in ramps-studio, copied
// outward. Don't edit it downstream.
// ==============================================
import { cn } from "../utils"

const INK = "#131210"

/**
 * Figures, in the 32-unit viewBox the plate defines.
 *
 * A tool with no mark yet renders the bare plate rather than a placeholder
 * glyph — an invented symbol for an unbuilt tool is a promise about what it
 * will be, and these are quiet enough to read as "not yet".
 */
const FIGURES: Record<string, React.ReactNode> = {
  ramps: (
    <>
      <rect x="6" y="6" width="20" height="4" rx="1.2" fill="#c5d9ff" />
      <rect x="6" y="11" width="20" height="4" rx="1.2" fill="#8db0ff" />
      <rect x="6" y="16" width="20" height="4" rx="1.2" fill="#3d7dff" />
      <rect x="6" y="21" width="20" height="4" rx="1.2" fill="#2452b0" />
    </>
  ),
  // Five bars at irregular heights. Same shape as beeps.studio/favicon.svg,
  // generated by that repo's scripts/build-icons.py — change one, change both.
  //
  // It was a decaying oscillation drawn as one continuous stroke, which read
  // as a near-twin of the motion curve below: same colour, same weight, same
  // kind of drawing. Bars are a different object at a glance, and they rhyme
  // with Ramps' four horizontal bars turned a quarter turn.
  //
  // The heights are deliberately IRREGULAR — a smooth fall reads as a level
  // meter, and real audio is not monotonic.
  sound: (
    <>
      <rect x="6.00" y="11.50" width="2.8" height="9" rx="1.1" fill="#8db0ff" />
      <rect x="10.30" y="6.00" width="2.8" height="20" rx="1.1" fill="#8db0ff" />
      <rect x="14.60" y="10.00" width="2.8" height="12" rx="1.1" fill="#8db0ff" />
      <rect x="18.90" y="7.50" width="2.8" height="17" rx="1.1" fill="#8db0ff" />
      <rect x="23.20" y="12.50" width="2.8" height="7" rx="1.1" fill="#8db0ff" />
    </>
  ),
  // A spring's step response, as two stacked strokes. Same point lists as
  // springs.studio/favicon.svg — change one, change both.
  //
  // A single stroke carried far less weight than Ramps' four filled bars, so
  // the two did not read as equals side by side. Filling the area beneath read
  // as a blob rather than a curve, and a heavy stroke with a lighter core read
  // as an outline. A parallel pair keeps it a LINE while giving it Ramps' kind
  // of density, and it rhymes with the four bars there and the five in Beeps —
  // the family is stacked strokes, in every mark.
  //
  // The lower stroke is the upper one TRANSLATED STRAIGHT DOWN, not offset
  // along its normal, and that is load-bearing: a normal offset folds back
  // through itself wherever the offset exceeds the local radius of curvature,
  // which at the overshoot peak is about 0.6 units against a 2.4-unit offset.
  // That left a visible cusp on the lower stroke. Translating cannot fold, and
  // it makes the two exactly the same shape rather than near-twins.
  motion: (
    <>
      <polyline
        points="7.45,19.75 7.64,19.71 7.84,19.60 8.03,19.42 8.23,19.18 8.42,18.88 8.62,18.53 8.81,18.14 9.00,17.70 9.20,17.23 9.39,16.73 9.59,16.21 9.78,15.67 9.98,15.12 10.17,14.56 10.36,14.01 10.56,13.45 10.75,12.90 10.95,12.37 11.14,11.85 11.34,11.35 11.53,10.87 11.73,10.42 11.92,9.99 12.11,9.59 12.31,9.23 12.50,8.90 12.70,8.60 12.89,8.34 13.09,8.11 13.28,7.92 13.47,7.76 13.67,7.63 13.86,7.54 14.06,7.48 14.25,7.45 14.45,7.45 14.64,7.48 14.83,7.53 15.03,7.61 15.22,7.71 15.42,7.83 15.61,7.97 15.81,8.13 16.00,8.30 16.19,8.48 16.39,8.67 16.58,8.87 16.78,9.07 16.97,9.28 17.17,9.49 17.36,9.69 17.55,9.90 17.75,10.10 17.94,10.30 18.14,10.49 18.33,10.67 18.53,10.84 18.72,11.01 18.91,11.16 19.11,11.30 19.30,11.43 19.50,11.55 19.69,11.65 19.89,11.74 20.08,11.82 20.28,11.89 20.47,11.94 20.66,11.98 20.86,12.01 21.05,12.02 21.25,12.03 21.44,12.02 21.64,12.01 21.83,11.98 22.02,11.95 22.22,11.91 22.41,11.86 22.61,11.80 22.80,11.74 23.00,11.68 23.19,11.61 23.38,11.53 23.58,11.46 23.77,11.38 23.97,11.31 24.16,11.23 24.36,11.15 24.55,11.08"
        fill="none"
        stroke="#8db0ff"
        strokeWidth="2.9"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <polyline
        points="7.45,24.55 7.64,24.51 7.84,24.40 8.03,24.22 8.23,23.98 8.42,23.68 8.62,23.33 8.81,22.94 9.00,22.50 9.20,22.03 9.39,21.53 9.59,21.01 9.78,20.47 9.98,19.92 10.17,19.36 10.36,18.81 10.56,18.25 10.75,17.70 10.95,17.17 11.14,16.65 11.34,16.15 11.53,15.67 11.73,15.22 11.92,14.79 12.11,14.39 12.31,14.03 12.50,13.70 12.70,13.40 12.89,13.14 13.09,12.91 13.28,12.72 13.47,12.56 13.67,12.43 13.86,12.34 14.06,12.28 14.25,12.25 14.45,12.25 14.64,12.28 14.83,12.33 15.03,12.41 15.22,12.51 15.42,12.63 15.61,12.77 15.81,12.93 16.00,13.10 16.19,13.28 16.39,13.47 16.58,13.67 16.78,13.87 16.97,14.08 17.17,14.29 17.36,14.49 17.55,14.70 17.75,14.90 17.94,15.10 18.14,15.29 18.33,15.47 18.53,15.64 18.72,15.81 18.91,15.96 19.11,16.10 19.30,16.23 19.50,16.35 19.69,16.45 19.89,16.54 20.08,16.62 20.28,16.69 20.47,16.74 20.66,16.78 20.86,16.81 21.05,16.82 21.25,16.83 21.44,16.82 21.64,16.81 21.83,16.78 22.02,16.75 22.22,16.71 22.41,16.66 22.61,16.60 22.80,16.54 23.00,16.48 23.19,16.41 23.38,16.33 23.58,16.26 23.77,16.18 23.97,16.11 24.16,16.03 24.36,15.95 24.55,15.88"
        fill="none"
        stroke="#3d7dff"
        strokeWidth="2.9"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </>
  ),
}

export default function ToolMark({
  id,
  size = 16,
  className,
}: {
  /** Tool id from the manifest. An unknown id renders the bare plate. */
  id: string
  size?: number
  className?: string
}) {
  return (
    <svg
      viewBox="0 0 32 32"
      width={size}
      height={size}
      aria-hidden="true"
      focusable="false"
      className={cn("shrink-0", className)}
    >
      <rect width="32" height="32" rx="7" fill={INK} />
      {FIGURES[id] ?? null}
    </svg>
  )
}
